<a href="https://colab.research.google.com/github/Bus-RaRa/deeplearningcode2/blob/main/DL_argmin_mean_variance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import torch.nn as nn


# ARGMIN/ARGMAX USING NUMPY

In [4]:
#create a vector
v = np.array([1,40,2,-3])

In [7]:
#find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('Min,max: %g,%g' %(minval,maxval))

#now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min,max indices: %g %g'%(minidx,maxidx)) , print('')

Min,max: -3,40
Min,max indices: 3 1



(None, None)

In [11]:
#now, for a matrix:
M = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(M), print('')

minvals = np.argmin(M)#minimum for the entire matrix
minvals1 = np.argmin(M,axis=0) #minimum of each column
maxvals1 = np.argmax(M,axis=0)

minvals2 = np.argmin(M,axis=1) #minimum of each row
maxvals2 = np.argmax(M,axis=1)
print(minvals), print('')
print(minvals1), print('')
print(minvals2), print('')
print(maxvals1), print('')
print(maxvals2), print('')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0

[0 0 0]

[0 0 0]

[2 2 2]

[2 2 2]



(None, None)

# USING PYKEY

In [17]:
#create a vector
v = torch.tensor([[1,2,40,-3],[5,9,1,2]])

#find and report the maximum and minumum values
minval = torch.min(v)
maxval = torch.max(v)
min1 = torch.min(v,axis=0)
min2 = torch.min(v,axis=1)
max1 = torch.max(v,axis=0)
max2 = torch.max(v,axis=1)

print('Min,max: %g,%g' %(minval,maxval))
print(min1), print('')
print(min2), print('')
print(max1), print('')
print(max2), print('')
print(min1.values), print('')
print(min1.indices)

Min,max: -3,40
torch.return_types.min(
values=tensor([ 1,  2,  1, -3]),
indices=tensor([0, 0, 1, 0]))

torch.return_types.min(
values=tensor([-3,  1]),
indices=tensor([3, 2]))

torch.return_types.max(
values=tensor([ 5,  9, 40,  2]),
indices=tensor([1, 1, 0, 1]))

torch.return_types.max(
values=tensor([40,  9]),
indices=tensor([2, 1]))

tensor([ 1,  2,  1, -3])

tensor([0, 0, 1, 0])


#MEAN AND VARIANCE

In [25]:
x = [1,2,4,6,5,4,0]
n = len(x)

#computate the mean
mean1 = np.mean(x)
print(mean1)

#compute the variance
var1 = np.var(x)
print(var1)
var2 = (1/(n-1)) * np.sum((x-mean1)**2) #biased variance so different outputs
print(var2)

3.142857142857143
4.122448979591836
4.809523809523809


In [26]:
var3 = np.var(x,ddof=1) #unbiased variance
print(var3)
print(var2)

4.809523809523809
4.809523809523809


In [24]:
#the differance gets smaller for larger datasets.